"""Project lifecycle for the flat Che layout.

A **project** is an organising abstraction with a stable slug and a folder under
``~/.che-workspaces/<slug>/``. It deliberately does NOT bind a filesystem path —
only a **worktree** does (see :mod:`che_core.worktrees`). The L1 "workspace"
grouping level was retired in Sep 2026: projects live directly under the storage
root, and each project owns a folder per canonical domain plus a ``worktrees/``
folder.
"""

import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from che_core.paths import _slugify, get_workspaces_root
from che_core.project_layout import (
    DOMAIN_SLUGS,
    get_db_dir,
    get_project_dir,
    get_roles_dir,
    get_trash_dir,
    git_origin,
    is_git_repo,
    normalise_domain,
    validate_slug,
)
from che_core.worktrees import (
    add_worktree,
    ensure_project_skeleton,
    list_worktrees,
)

ARCHITECTURE_MD_TEMPLATE = """# Architecture — {project_slug}

> Generated by `che project init` · {ts}

## 1. System Context (C4 L1)

<!-- TODO: Describe the system + users + upstream/downstream systems. -->

## 2. Containers (C4 L2)

<!-- TODO: Break down into web / API / DB / workers. -->

## 3. Key Decisions (ADR index)

| # | Title | Status |
|---|---|---|
| ADR-0001 | <!-- fill in --> | Proposed |

## 4. Data Model

<!-- TODO: ERD or textual entity list + relationships. -->

## 5. Quality Attributes

- **Security**: <!-- e.g. RLS, auth provider, secrets -->
- **Performance**: <!-- e.g. latency budgets, cache strategy -->
- **Observability**: <!-- e.g. Sentry, logs, metrics -->
- **Compliance**: <!-- e.g. GDPR/LGPD, PCI, WCAG -->
"""


PROJECT_PROFILE_MD_TEMPLATE = """# Project Profile — {project_slug}

> Generated by `che project init` · {ts}

## Identification

- Slug: `{project_slug}`
- Detected stack: `{stack}`
- Primary domain (default): `{domain}`
- Source repository (git): `{origin}`

## Stack / Patterns

<!-- Edit: language, frameworks, package manager, test runner, CI provider. -->
- Language: <!-- e.g. Python 3.12 / TypeScript 5 / Go 1.23 -->
- Framework(s): <!-- e.g. Next.js 15 / FastAPI / NestJS -->
- Package manager: <!-- e.g. corepack pnpm / uv / cargo -->
- Task runner: <!-- e.g. Nx / turbo / Makefile / just -->
- Test runner: <!-- e.g. Vitest / pytest / jest -->
- CI/CD: <!-- e.g. GitHub Actions / Vercel / Railway -->

## Deployment

- Environments: dev · preview · staging · prod
- Deploy target: <!-- e.g. Vercel / Railway / AWS / self-hosted -->
- Primary database: <!-- e.g. Postgres 16 / Supabase / SQLite -->
- Cache / queues: <!-- e.g. Redis / RabbitMQ / SQS -->
- Env vars: <!-- list NON-SECRET keys from .env.example -->

## Roles / Policies

See `roles/index.md` for the authoritative owner.
"""


ROLES_MD_TEMPLATE = """# Roles & Codeowners — {project_slug}

> Generated by `che project init` · {ts}

| Role | Person (GitHub / handle) | Ownership scope |
|---|---|---|
| Product Owner | <!-- @handle --> | PRD, roadmap, AC sign-off |
| Tech Lead | <!-- @handle --> | Architecture, ADRs, code review |
| Design Owner | <!-- @handle --> | Design system, accessibility (WCAG 2.2 AA) |
| DevOps / Infra | <!-- @handle --> | CI, variables, deploy targets |
| QA Owner | <!-- @handle --> | Playwright, regression, release gate |

## Default domain

Default domain for the task graph when an envelope does not declare one: `{domain}`
"""


ROADMAP_MD_TEMPLATE = """# Roadmap — {project_slug}

> Generated by `che project init` · {ts}

## Now (≤4 weeks)

<!-- list Epic → ticket link Linear/ClickUp/GitHub → AC -->

## Next (4-12 weeks)

<!-- list Epic → priority → depends on -->

## Later (≥12 weeks)

<!-- non-prioritized ideas -->
"""


PRODUCT_CONTEXT_MD_TEMPLATE = """# Product Context — {project_slug}

> Generated by `che project init` · {ts}

## Elevator Pitch

<!-- 2-3 sentences: who is the user, what pain it solves, unique benefit. -->

## Key Personas

| ID | Name | Profile | Jobs To Be Done (top 3) |
|---|---|---|---|
| P1 | <!-- --> | <!-- --> | 1. … 2. … 3. … |

## Success Metrics (North Star + 3 lagging)

1. **North Star**: <!-- e.g. tickets scanned per event per week -->
2. <!-- -->
3. <!-- -->
4. <!-- -->

## Fixed Constraints (non-negotiable)

- Currency: <!-- e.g. GBP · BRL · USD -->
- Localization: <!-- e.g. pt-BR · en-GB · Europe/London -->
- Compliance: <!-- e.g. GDPR · LGPD · PCI -->
- Accessibility: <!-- e.g. WCAG 2.2 AA target -->
"""


DB_README_TXT = """SQLite files managed by Che (FTS5 state store + RAG vector store).

THIS FOLDER IS PROJECT-DURABLE: it survives branch / worktree switches within the same project.

- che_state.sqlite  → FTS5 full-text index over decisions.log + task_graph + specs + envelopes.
                    SSOT is the filesystem (project docs + worktree shared docs).
                    Rebuildable at any time: `che state rebuild-index --worktree-root <path>`.

- che_rag.sqlite    → (optional) RAG embeddings vector store (sqlite-vec).
                    Rebuildable at any time: `che rag build-index <path> --provider=none`.

Portability rules:
  Export by default DOES NOT include databases. To include: `che export <path> <out> --include-db`.
  Default limit 250MB for the sum of both; above: generates a SKIPPED.txt file in this folder.
"""


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ts_slug() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def _detect_stack(repo_root: Optional[str]) -> str:
    if not repo_root:
        return "unknown"
    wt = Path(repo_root).expanduser().resolve()
    probes = {
        "Next.js/React (monorepo pnpm)": ["pnpm-workspace.yaml", "pnpm-lock.yaml"],
        "Node.js/npm": ["package-lock.json"],
        "Node.js/yarn": ["yarn.lock"],
        "Python (uv)": ["uv.lock", "pyproject.toml"],
        "Python (pip/poetry)": ["requirements.txt", "poetry.lock"],
        "Go": ["go.mod"],
        "Rust": ["Cargo.toml"],
    }
    found: List[str] = []
    for label, files in probes.items():
        for f in files:
            if (wt / f).exists():
                found.append(label)
                break
    if not found:
        return "generic"
    return ", ".join(sorted(set(found)))


# --- Trash (shared by project + worktree removals) ---------------------------


def _trash_dir() -> Path:
    t = get_trash_dir()
    t.mkdir(parents=True, exist_ok=True)
    return t


def _write_manifest(trash_target: Path, *, kind: str, original_path: str, slug: str) -> None:
    manifest = {
        "kind": kind,
        "slug": slug,
        "original_path": original_path,
        "moved_at": _timestamp(),
        "restore_hint": f"che project restore {slug}",
    }
    with open(trash_target / "_MANIFEST.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)


def _read_manifest(trash_target: Path) -> Dict[str, Any]:
    mp = trash_target / "_MANIFEST.json"
    if not mp.is_file():
        return {}
    try:
        with open(mp, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def list_trash() -> List[Dict[str, Any]]:
    t = _trash_dir()
    out = []
    for d in sorted(t.iterdir()):
        if not d.is_dir():
            continue
        mf = _read_manifest(d)
        mf.setdefault("trash_path", str(d))
        mf.setdefault("slug", d.name)
        out.append(mf)
    return out


# --- Project lifecycle -------------------------------------------------------


def init_project(
    repo_path: str,
    *,
    slug: str,
    domain: str = "engineering",
    friendly_name: Optional[str] = None,
) -> Dict[str, Any]:
    """Create (or refresh) a flat project for a git repository.

    Preconditions:
      - ``slug`` is an explicit valid slug (never inferred from ambient state).
      - ``repo_path`` is a directory inside a git working tree.

    Postcondition: ``~/.che-workspaces/<slug>/`` holds one folder per canonical
    domain plus ``worktrees/``, ``_db/`` and ``roles/``; the durable project docs
    exist; the project registry has a ``PROJECT_INIT`` entry. Idempotent — existing
    documents are never overwritten.
    """
    if not repo_path:
        print("init_project: `repo_path` is required.", file=sys.stderr)
        sys.exit(2)

    try:
        validate_slug(slug, label="--slug")
    except ValueError as exc:
        print(f"init_project: {exc}", file=sys.stderr)
        sys.exit(2)

    try:
        canonical_domain = normalise_domain(domain)
    except ValueError as exc:
        print(f"init_project: {exc}", file=sys.stderr)
        sys.exit(2)

    repo = Path(repo_path).expanduser().resolve()
    if not repo.is_dir():
        print(f"init_project: repo_path={repo} is not a directory.", file=sys.stderr)
        sys.exit(2)

    if not is_git_repo(str(repo)):
        print(
            f"init_project: {repo} is not a git repository. "
            "Che projects require git (contract R4); nothing was created.",
            file=sys.stderr,
        )
        sys.exit(2)

    project_dir = get_project_dir(slug)
    already_existed = project_dir.is_dir()

    skeleton = ensure_project_skeleton(slug)
    created_files: List[str] = []

    ts = _timestamp()
    fmt_vars = {
        "project_slug": slug,
        "ts": ts,
        "stack": _detect_stack(str(repo)),
        "domain": canonical_domain,
        "origin": git_origin(str(repo)) or f"local/{repo.name}",
    }

    for filename, template in (
        ("architecture.md", ARCHITECTURE_MD_TEMPLATE),
        ("project_profile.md", PROJECT_PROFILE_MD_TEMPLATE),
        ("product_context.md", PRODUCT_CONTEXT_MD_TEMPLATE),
        ("roadmap.md", ROADMAP_MD_TEMPLATE),
    ):
        target = project_dir / filename
        if not target.is_file():
            target.write_text(template.format(**fmt_vars), encoding="utf-8")
            created_files.append(str(target))

    roles_file = get_roles_dir(slug) / "index.md"
    if not roles_file.is_file():
        roles_file.write_text(ROLES_MD_TEMPLATE.format(**fmt_vars), encoding="utf-8")
        created_files.append(str(roles_file))

    db_readme = get_db_dir(slug) / "README.txt"
    if not db_readme.is_file():
        db_readme.write_text(DB_README_TXT, encoding="utf-8")
        created_files.append(str(db_readme))

    registry_file = project_dir / "registry.jsonl"
    if not registry_file.is_file():
        registry_file.touch()
        created_files.append(str(registry_file))

    if registry_file.stat().st_size == 0:
        entry = {
            "ts": ts,
            "event": "PROJECT_INIT",
            "project_slug": slug,
            "friendly_name": friendly_name or slug,
            "domain": canonical_domain,
            "repo_root": str(repo),
            "origin": fmt_vars["origin"],
            "stack": fmt_vars["stack"],
        }
        with open(registry_file, "a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False, sort_keys=True) + "\n")

    return {
        "initialised": True,
        "already_existed": already_existed,
        "project_slug": slug,
        "friendly_name": friendly_name or slug,
        "domain": canonical_domain,
        "project_dir": str(project_dir),
        "repo_root": str(repo),
        "domains": list(DOMAIN_SLUGS),
        "skeleton_created": skeleton["created"],
        "files_created": created_files,
        "next_steps": [
            f"1. Fill in the durable docs under {project_dir}.",
            f"2. Bind your checkout: che worktree add {repo} --project {slug} --name main",
            "3. Edit the domain handoff docs under the matching domain folder.",
        ],
    }


def _looks_like_project(project_dir: Path) -> bool:
    """Heuristic guard so pre-flattening leftovers are not reported as projects.

    A flat project always carries a ``registry.jsonl`` and/or a ``worktrees/``
    folder at its root. Legacy workspace folders (``<root>/<workspace>/<project>/``
    and ``<root>/<workspace>/<worktree>/.wt/``) carry neither, so they are skipped
    instead of being silently misread as projects.
    """
    return (project_dir / "registry.jsonl").is_file() or (project_dir / "worktrees").is_dir()


def list_projects() -> List[Dict[str, Any]]:
    """Every flat project folder, with its docs, worktrees and DB files.

    Folders under the storage root that are not flat projects (legacy workspace
    leftovers) are reported separately under ``legacy_untouched`` so nothing is
    silently ignored — Che never removes them on its own.
    """
    root = get_workspaces_root()
    if not root.is_dir():
        return []

    out: List[Dict[str, Any]] = []
    legacy: List[str] = []
    for project_dir in sorted(root.iterdir()):
        if not project_dir.is_dir() or project_dir.name.startswith("."):
            continue
        slug = project_dir.name
        try:
            validate_slug(slug)
        except ValueError:
            # Uppercase / otherwise invalid folder names cannot be project slugs.
            legacy.append(slug)
            continue

        if not _looks_like_project(project_dir):
            legacy.append(slug)
            continue

        db_dir = project_dir / "_db"
        out.append(
            {
                "slug": slug,
                "path": str(project_dir),
                "architecture_exists": (project_dir / "architecture.md").is_file(),
                "project_profile_exists": (project_dir / "project_profile.md").is_file(),
                "db_files": sorted(p.name for p in db_dir.glob("*")) if db_dir.is_dir() else [],
                "worktrees": [w.get("name") for w in list_worktrees(slug)],
                "domains": sorted(d.name for d in project_dir.iterdir() if d.is_dir() and d.name in DOMAIN_SLUGS),
            }
        )

    if legacy:
        out.append(
            {
                "legacy_untouched": legacy,
                "note": (
                    "These folders do not look like flat projects (no registry.jsonl / worktrees/). "
                    "They are pre-flattening leftovers and were left untouched. "
                    "Re-create them with `che project init <repo> --slug <slug>` and move the old "
                    "folder to `.trash/` once you are satisfied."
                ),
            }
        )
    return out


def remove_project(
    project_slug: str,
    *,
    dry_run: bool = True,
    confirmed: bool = False,
) -> Dict[str, Any]:
    """Trash-safe removal of a project folder (never ``rm -rf``)."""
    project_dir = get_project_dir(project_slug)
    bound = list_worktrees(project_slug)

    plan = {
        "action": "move-to-trash",
        "project": project_slug,
        "from": str(project_dir),
        "bound_worktrees": [w.get("path") for w in bound],
        "repos_untouched": True,
        "dry_run": dry_run,
    }

    if not project_dir.is_dir():
        print(f"remove_project: project {project_slug!r} does not exist.", file=sys.stderr)
        sys.exit(3)

    if dry_run:
        plan["applied"] = False
        plan["next"] = "Re-run with --no-dry-run --confirm to apply."
        return plan

    if not confirmed:
        print("remove_project: refusing to apply without --confirm.", file=sys.stderr)
        sys.exit(2)

    trash_root = _trash_dir()
    trash_slug = f"project--{project_slug}--{_ts_slug()}"
    trash_target = trash_root / trash_slug
    shutil.move(str(project_dir), str(trash_target))
    _write_manifest(trash_target, kind="project", original_path=str(project_dir), slug=trash_slug)

    plan.update({"applied": True, "trash_path": str(trash_target), "trash_slug": trash_slug})
    return plan


def restore_project(trash_slug: str) -> Dict[str, Any]:
    """Move a trashed project back to its original flat location."""
    trash_target = _trash_dir() / trash_slug
    if not trash_target.is_dir():
        print(f"restore_project: trash entry {trash_slug!r} not found.", file=sys.stderr)
        sys.exit(3)

    manifest = _read_manifest(trash_target)
    original = manifest.get("original_path")
    if not original:
        print(f"restore_project: no original_path in manifest of {trash_slug!r}.", file=sys.stderr)
        sys.exit(3)

    target = Path(original)
    if target.exists():
        print(f"restore_project: target {target} already exists — refusing to overwrite.", file=sys.stderr)
        sys.exit(3)

    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(trash_target), str(target))
    return {"restored": True, "trash_slug": trash_slug, "restored_to": str(target)}


# --- Hook helpers (git worktree add/remove) ----------------------------------


def ensure_worktree_l3_dirs(worktree_root: str, *, session_id: str = "auto-worktree-bootstrap") -> Dict[str, Any]:
    """React to ``git worktree add`` by binding the new checkout when we can infer it.

    Inference is intentionally conservative: the repo's ``origin`` must match a
    project that already exists. Otherwise we return a note telling the user to run
    ``che worktree add`` explicitly, rather than guessing a project.
    """
    del session_id  # sessions no longer own folders; kept for call-site compatibility
    repo = Path(worktree_root).expanduser().resolve()

    origin = git_origin(str(repo))
    if not origin:
        return {"bound": False, "note": f"{repo} has no git origin — cannot infer a project."}

    candidates = {p["slug"] for p in list_projects() if "slug" in p}
    for slug in candidates:
        project_dir = get_project_dir(slug)
        registry_file = project_dir / "registry.jsonl"
        if not registry_file.is_file():
            continue
        try:
            lines = registry_file.read_text(encoding="utf-8").strip().splitlines()
        except OSError:
            continue
        for line in lines:
            try:
                entry = json.loads(line)
            except Exception:
                continue
            if entry.get("event") == "PROJECT_INIT" and entry.get("origin") == origin:
                name = _slugify(repo.name) or "main"
                result = add_worktree(slug, str(repo), name)
                return {"bound": True, "project": slug, "worktree": name, **result}

    return {
        "bound": False,
        "note": (
            f"No Che project matches origin={origin}. "
            f"Bind explicitly: che worktree add {repo} --project <project> --name <name>"
        ),
    }


def cleanup_worktree_l3(worktree_root: str) -> Dict[str, Any]:
    """Report the Che worktrees bound to a checkout being removed (no destructive action)."""
    from che_core.worktrees import find_worktree_by_path

    matches = find_worktree_by_path(worktree_root)
    return {
        "unbound": False,
        "found": [{"project": m.get("project"), "worktree": m.get("name")} for m in matches],
        "note": (
            "Run `che worktree remove <project> <name> --no-dry-run --confirm` to retire the Che side."
            if matches
            else "No Che worktree bound to this path."
        ),
    }
