import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from che_core.paths import (
    _slugify,
    compute_paths,
    ensure_session_dirs,
    get_workspaces_root,
    project_slug_from_git_origin,
    resolve_workspace_name,
    resolve_worktree_slug,
)

ARCHITECTURE_MD_TEMPLATE = """# Architecture — {project_slug}

> Generated by `che project init` · {ts}

## 1. System Context (C4 L1)

<!-- TODO: Describe the system + users + upstream/downstream systems. -->

## 2. Containers (C4 L2)

<!-- TODO: Break down into web / API / DB / workers. -->

## 3. Key Decisions (ADR index)

| # | Title | Status |
|---|---|---|
| ADR-0001 | <!-- fill in --> | Proposed |

## 4. Data Model

<!-- TODO: ERD or textual entity list + relationships. -->

## 5. Quality Attributes

- **Security**: <!-- e.g. RLS, auth provider, secrets -->
- **Performance**: <!-- e.g. latency budgets, cache strategy -->
- **Observability**: <!-- e.g. Sentry, logs, metrics -->
- **Compliance**: <!-- e.g. GDPR/LGPD, PCI, WCAG -->
"""


PROJECT_PROFILE_MD_TEMPLATE = """# Project Profile — {project_slug}

> Generated by `che project init` · {ts}

## Identification

- Slug: `{project_slug}`
- Detected stack: `{stack}`
- Primary domain (Politburo default): `{domain}`
- Source repository (git): `{origin}`
- Source workspace: `{workspace}`

## Stack / Patterns

<!-- Edit: language, frameworks, package manager, test runner, CI provider. -->
- Language: <!-- e.g. Python 3.12 / TypeScript 5 / Go 1.23 -->
- Framework(s): <!-- e.g. Next.js 15 / FastAPI / NestJS -->
- Package manager: <!-- e.g. corepack pnpm / uv / cargo -->
- Task runner: <!-- e.g. Nx / turbo / Makefile / just -->
- Test runner: <!-- e.g. Vitest / pytest / jest -->
- CI/CD: <!-- e.g. GitHub Actions / Vercel / Railway -->

## Deployment

- Environments: dev · preview · staging · prod
- Deploy target: <!-- e.g. Vercel / Railway / AWS / self-hosted -->
- Primary database: <!-- e.g. Postgres 16 / Supabase / SQLite -->
- Cache / queues: <!-- e.g. Redis / RabbitMQ / SQS -->
- Env vars: <!-- list NON-SECRET keys from .env.example -->

## Roles / Policies

- Product Owner (PM): <!-- @user -->
- Head Engineer: <!-- @user -->
- Design / UX owner: <!-- @user -->
- GitHub Codeowner: <!-- @user (mandatory for CODEOWNERS) -->
"""


ROLES_MD_TEMPLATE = """# Roles & Codeowners — {project_slug}

> Generated by `che project init` · {ts}

| Role | Person (GitHub / handle) | Ownership scope |
|---|---|---|
| Product Owner | <!-- @handle --> | PRD, roadmap, AC sign-off |
| Tech Lead | <!-- @handle --> | Architecture, ADRs, code review |
| UX Designer | <!-- @handle --> | Figma, accessibility (WCAG 2.2 AA) |
| DevOps / Infra | <!-- @handle --> | CI, variables, Vercel/Railway |
| QA Owner | <!-- @handle --> | Playwright, regression, release gate |

## Politburo default domain

Default domain for task graph when the envelope does not explicitly declare one: `{domain}`
"""


ROADMAP_MD_TEMPLATE = """# Roadmap — {project_slug}

> Generated by `che project init` · {ts}

## Now (≤4 weeks)

<!-- list Epic → ticket link Linear/ClickUp/GitHub → AC -->

## Next (4-12 weeks)

<!-- list Epic → priority → depends on -->

## Later (≥12 weeks)

<!-- non-prioritized ideas -->
"""


PRODUCT_CONTEXT_MD_TEMPLATE = """# Product Context — {project_slug}

> Generated by `che project init` · {ts}

## Elevator Pitch

<!-- 2-3 sentences: who is the user, what pain it solves, unique benefit. -->

## Key Personas

| ID | Name | Profile | Jobs To Be Done (top 3) |
|---|---|---|---|
| P1 | <!-- --> | <!-- --> | 1. … 2. … 3. … |

## Success Metrics (North Star + 3 lagging)

1. **North Star**: <!-- e.g. tickets scanned per event per week -->
2. <!-- -->
3. <!-- -->
4. <!-- -->

## Fixed Constraints (non-negotiable)

- Currency: <!-- e.g. GBP · BRL · USD -->
- Localization: <!-- e.g. pt-BR · en-GB · Europe/London -->
- Compliance: <!-- e.g. GDPR · LGPD · PCI -->
- Accessibility: <!-- e.g. WCAG 2.2 AA target -->
"""


DB_README_TXT = """SQLite files managed by Che (FTS5 state store + RAG vector store).

THIS FOLDER IS L2 DURABLE: survives branch / worktree switches within the same project.

- che_state.sqlite  → FTS5 full-text index over decisions.log + task_graph + specs + envelopes.
                    SSOT is the filesystem in L2 (docs) + L3 (worktree shared).
                    Rebuildable at any time: `che state rebuild-index`.

- che_rag.sqlite    → (optional) RAG embeddings vector store (sqlite-vec).
                    Rebuildable at any time: `che rag build-index --provider=none`.

Portability rules:
  Export by default DOES NOT include databases. To include: `che-export --include-db`.
  Default limit 250MB for the sum of both; above: generates a SKIPPED.txt file in this folder.
"""


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _ts_slug() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def _detect_stack(worktree_root: Optional[str]) -> str:
    if not worktree_root:
        return "unknown"
    wt = Path(worktree_root).resolve()
    probes = {
        "Next.js/React (monorepo pnpm)": ["pnpm-workspace.yaml", "pnpm-lock.yaml"],
        "Node.js/npm": ["package-lock.json"],
        "Node.js/yarn": ["yarn.lock"],
        "Python (uv)": ["uv.lock", "pyproject.toml"],
        "Python (pip/poetry)": ["requirements.txt", "poetry.lock"],
        "Go": ["go.mod"],
        "Rust": ["Cargo.toml"],
    }
    founds: List[str] = []
    for label, files in probes.items():
        for f in files:
            if (wt / f).exists():
                founds.append(label)
                break
    if not founds:
        return "generic"
    return ", ".join(sorted(set(founds)))


def _git_origin_of(worktree_root: Optional[str]) -> str:
    import subprocess

    if not worktree_root:
        return "local-only (no git)"
    try:
        res = subprocess.run(
            ["git", "-C", worktree_root, "remote", "get-url", "origin"],
            capture_output=True,
            text=True,
            check=False,
        )
        if res.returncode == 0 and res.stdout.strip():
            return res.stdout.strip()
    except Exception:
        pass
    return "local-only (no git origin)"


def list_workspaces() -> List[Dict[str, Any]]:
    ws_root = get_workspaces_root() / "workspaces"
    if not ws_root.is_dir():
        return []
    out = []
    for d in sorted(ws_root.iterdir()):
        if not d.is_dir():
            continue
        # Only list top-level directories in 'workspaces/' as workspace names
        projects = sorted([p.name for p in d.iterdir() if p.is_dir() and (p / "project").is_dir()])
        out.append(
            {
                "name": d.name,
                "path": str(d),
                "projects_count": len(projects),
                "projects": projects[:20],
            }
        )
    return out


def add_workspace(name: str, *, worktree_root: Optional[str] = None) -> Dict[str, Any]:
    if not name:
        print("add_workspace: `name` is required.", file=sys.stderr)
        sys.exit(2)
    slug = _slugify(name) or "default"
    ws_root = get_workspaces_root() / "workspaces"
    ws_dir = ws_root / slug
    created = False
    if not ws_dir.is_dir():
        ws_dir.mkdir(parents=True, exist_ok=True)
        created = True
    return {
        "name": slug,
        "path": str(ws_dir),
        "created": created,
        "workspace_dir_exists": ws_dir.is_dir(),
        "hint_if_first_project": "Now run `che project init <worktree>` inside a repo to create L2.",
    }


def _trash_dir() -> Path:
    t = get_workspaces_root() / ".trash"
    t.mkdir(parents=True, exist_ok=True)
    return t


def _write_manifest(trash_target: Path, *, kind: str, original_path: str, slug: str) -> None:
    manifest = {
        "kind": kind,
        "slug": slug,
        "original_path": original_path,
        "moved_at": _timestamp(),
        "restore_hint": f"che workspace restore {slug} (or `che project restore {slug}`)",
    }
    with open(trash_target / "_MANIFEST.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)


def _read_manifest(trash_target: Path) -> Dict[str, Any]:
    mp = trash_target / "_MANIFEST.json"
    if not mp.is_file():
        return {}
    try:
        with open(mp, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def list_trash() -> List[Dict[str, Any]]:
    t = _trash_dir()
    out = []
    for d in sorted(t.iterdir()):
        if not d.is_dir():
            continue
        mf = _read_manifest(d)
        mf.setdefault("trash_path", str(d))
        mf.setdefault("slug", d.name)
        out.append(mf)
    return out


def remove_workspace(name: str, *, dry_run: bool = True, confirmed: bool = False) -> Dict[str, Any]:
    if not name:
        print("remove_workspace: `name` is required.", file=sys.stderr)
        sys.exit(2)
    slug = _slugify(name) or "default"
    ws_root = get_workspaces_root() / "workspaces"
    ws_dir = ws_root / slug
    if not ws_dir.is_dir():
        return {"error": f"Workspace '{slug}' does not exist in {ws_root}", "dry_run": dry_run}

    items = sorted(p.name for p in ws_dir.iterdir())
    total_bytes = sum(p.stat().st_size for p in ws_dir.rglob("*") if p.is_file())
    ts = _ts_slug()
    trash_name = f"workspace--{slug}--{ts}"
    trash_target = _trash_dir() / trash_name

    if dry_run:
        return {
            "dry_run": True,
            "action_would_be": "MOVE (not delete) to trash .trash/",
            "workspace": slug,
            "from": str(ws_dir),
            "to": str(trash_target),
            "items_inside": items,
            "total_bytes_approx": total_bytes,
            "gate": "Confirmation pending. Re-run WITHOUT --dry-run AND with confirmed=True.",
            "restore_command": f"che workspace restore {trash_name}",
        }

    if not confirmed:
        return {
            "dry_run": False,
            "aborted": True,
            "reason": "Gate §2 safety: confirmed=False. Re-execute with confirmed=True after dry-run review.",
            "dry_run_above_command": f"che workspace remove {slug} --dry-run",
        }

    trash_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(ws_dir), str(trash_target))
    _write_manifest(trash_target, kind="workspace", original_path=str(ws_dir), slug=trash_name)
    return {
        "dry_run": False,
        "moved": True,
        "workspace": slug,
        "from": str(ws_dir),
        "to": str(trash_target),
        "restore_command": f"che workspace restore {trash_name}",
    }


def restore_workspace(trash_slug: str) -> Dict[str, Any]:
    if not trash_slug:
        print("restore_workspace: `trash_slug` is required.", file=sys.stderr)
        sys.exit(2)
    trash_target = _trash_dir() / trash_slug
    if not trash_target.is_dir():
        return {"error": f"Trash entry not found: {trash_slug}"}
    mf = _read_manifest(trash_target)
    orig = mf.get("original_path")
    if not orig:
        return {"error": f"Corrupted trash manifest: missing original_path in {trash_target}"}
    orig_p = Path(orig)
    if orig_p.exists():
        ts = _ts_slug()
        return {
            "error": f"Original path already exists, will not overwrite: {orig}. Rename manually to avoid conflict (suggested suffix --{ts}).",
            "suggested_rename": f"mv {orig} {orig}--conflict--{ts}",
        }
    orig_p.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(trash_target), str(orig_p))
    manifest_bak = orig_p / "_MANIFEST.json"
    if manifest_bak.is_file():
        manifest_bak.unlink(missing_ok=True)
    return {
        "restored": True,
        "kind": mf.get("kind"),
        "from": str(trash_target),
        "to": str(orig_p),
    }


def list_projects(workspace_name: Optional[str] = None) -> List[Dict[str, Any]]:
    ws_root = get_workspaces_root() / "workspaces"
    if not ws_root.is_dir():
        return []

    out = []
    # If workspace_name is provided, only scan that workspace
    # Else scan all workspaces
    workspaces_to_scan = [ws_root / workspace_name] if workspace_name else ws_root.iterdir()

    for ws_dir in workspaces_to_scan:
        if not ws_dir.is_dir():
            continue

        for d in sorted(ws_dir.iterdir()):
            if not d.is_dir():
                continue

            project_l2 = d / "project"
            if not project_l2.is_dir():
                continue

            has_arch = (project_l2 / "architecture.md").is_file()
            has_profile = (project_l2 / "project_profile.md").is_file()
            db_dir = d / "_db"
            db_files = sorted([p.name for p in db_dir.glob("*.sqlite")]) if db_dir.is_dir() else []

            out.append(
                {
                    "slug": d.name,
                    "workspace": ws_dir.name,
                    "path": str(d),
                    "architecture_exists": has_arch,
                    "project_profile_exists": has_profile,
                    "db_files": db_files,
                }
            )
    return out


def init_project(
    worktree_root: str,
    *,
    workspace_name: Optional[str] = None,
    domain: str = "engineering",
    friendly_name: Optional[str] = None,
    session_id: str = "project-init-session",
) -> Dict[str, Any]:
    if not worktree_root:
        print("init_project: `worktree_root` is required.", file=sys.stderr)
        sys.exit(2)
    wt = Path(worktree_root).resolve()
    if not wt.is_dir():
        print(f"init_project: worktree_root={wt} is not a directory.", file=sys.stderr)
        sys.exit(2)

    project_slug = project_slug_from_git_origin(str(wt))
    workspace = workspace_name or resolve_workspace_name(str(wt))

    # Validate workspace existence
    ws_root = get_workspaces_root() / "workspaces"
    ws_dir = ws_root / workspace
    if not ws_dir.is_dir():
        return {
            "initialised": False,
            "error": f"Workspace '{workspace}' does not exist.",
            "suggestion": f"Create the workspace first with `che workspace create {workspace}` or check the name.",
            "workspace_missing": True,
            "requested_workspace": workspace,
        }

    # Fallback name logic: <workspace>--<folder>
    if not friendly_name:
        folder_name = wt.name
        friendly_name = f"{workspace}--{folder_name}"

    worktree_slug = resolve_worktree_slug(str(wt))

    paths = compute_paths(str(wt), session_id, cwd_override=str(wt))
    project_dir = Path(paths["CHE_PROJECT_DIR"])
    project_dir.mkdir(parents=True, exist_ok=True)

    created_files: List[str] = []

    ts = _timestamp()
    fmt_vars = {
        "project_slug": friendly_name,
        "ts": ts,
        "stack": _detect_stack(str(wt)),
        "domain": domain,
        "origin": _git_origin_of(str(wt)),
        "workspace": workspace,
    }

    arch_file = project_dir / "architecture.md"
    if not arch_file.is_file():
        arch_file.write_text(ARCHITECTURE_MD_TEMPLATE.format(**fmt_vars), encoding="utf-8")
        created_files.append(str(arch_file))

    prof_file = project_dir / "project_profile.md"
    if not prof_file.is_file():
        prof_file.write_text(PROJECT_PROFILE_MD_TEMPLATE.format(**fmt_vars), encoding="utf-8")
        created_files.append(str(prof_file))

    pc_file = project_dir / "product_context.md"
    if not pc_file.is_file():
        pc_file.write_text(PRODUCT_CONTEXT_MD_TEMPLATE.format(**fmt_vars), encoding="utf-8")
        created_files.append(str(pc_file))

    road_file = project_dir / "roadmap.md"
    if not road_file.is_file():
        road_file.write_text(ROADMAP_MD_TEMPLATE.format(**fmt_vars), encoding="utf-8")
        created_files.append(str(road_file))

    roles_dir = project_dir / "roles"
    roles_dir.mkdir(parents=True, exist_ok=True)
    roles_file = roles_dir / "index.md"
    if not roles_file.is_file():
        roles_file.write_text(ROLES_MD_TEMPLATE.format(**fmt_vars), encoding="utf-8")
        created_files.append(str(roles_file))

    reg_file = project_dir / "registry.jsonl"
    if not reg_file.is_file():
        reg_file.touch()
        created_files.append(str(reg_file))

    db_dir = project_dir.parent / "_db"
    db_dir.mkdir(parents=True, exist_ok=True)
    readme_db = db_dir / "README.txt"
    if not readme_db.is_file():
        readme_db.write_text(DB_README_TXT, encoding="utf-8")
        created_files.append(str(readme_db))

    ensure_session_dirs(str(wt), session_id, cwd_override=str(wt))

    return {
        "initialised": True,
        "project_slug": project_slug,
        "workspace": workspace,
        "worktree_slug": worktree_slug,
        "project_dir": str(project_dir),
        "worktree_root": str(wt),
        "friendly_name": friendly_name,
        "domain": domain,
        "files_created_count": len(created_files),
        "files_created": created_files,
        "already_existed_skipped": any(not (Path(p).is_file() and False) for p in created_files),
        "paths": {
            "CHE_PROJECT_DIR": paths["CHE_PROJECT_DIR"],
            "CHE_WORKSPACE_DIR": paths["CHE_WORKSPACE_DIR"],
            "CHE_WORKTREE_DIR": paths["CHE_WORKTREE_DIR"],
            "CHE_WORKSPACE_SHARED": paths["CHE_WORKSPACE_SHARED"],
        },
        "next_steps": [
            "1. Edit architecture.md / product_context.md / roadmap.md in CHE_PROJECT_DIR.",
            "2. Run `/che-onboarding` to add human context.",
            "3. Run `/che-architect` if designing a new system.",
            "4. When specs are ready: `/che-act` to raise multi-domain task graph.",
        ],
    }


def remove_project(
    project_slug: str, workspace_name: str, *, dry_run: bool = True, confirmed: bool = False
) -> Dict[str, Any]:
    if not project_slug:
        print("remove_project: `project_slug` is required.", file=sys.stderr)
        sys.exit(2)
    if not workspace_name:
        print("remove_project: `workspace_name` is required.", file=sys.stderr)
        sys.exit(2)

    slug = _slugify(project_slug) or project_slug
    ws_root = get_workspaces_root() / "workspaces"
    project_dir = ws_root / workspace_name / slug
    if not project_dir.is_dir():
        return {"error": f"Project L2 '{slug}' does not exist in {project_dir.parent}", "dry_run": dry_run}

    items = sorted(p.name for p in project_dir.iterdir())
    total_bytes = sum(p.stat().st_size for p in project_dir.rglob("*") if p.is_file())
    ts = _ts_slug()
    trash_name = f"project--{slug}--{ts}"
    trash_target = _trash_dir() / trash_name

    if dry_run:
        return {
            "dry_run": True,
            "action_would_be": "MOVE (not delete) to trash .trash/",
            "project": slug,
            "from": str(project_dir),
            "to": str(trash_target),
            "items_inside": items,
            "total_bytes_approx": total_bytes,
            "gate": "Confirmation pending. Re-run WITHOUT --dry-run AND with confirmed=True.",
            "restore_command": f"che project restore {trash_name}",
        }

    if not confirmed:
        return {
            "dry_run": False,
            "aborted": True,
            "reason": "Gate §2 safety: confirmed=False. Re-execute with confirmed=True after dry-run review.",
            "dry_run_above_command": f"che project remove {slug} --dry-run",
        }

    trash_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(project_dir), str(trash_target))
    _write_manifest(trash_target, kind="project", original_path=str(project_dir), slug=trash_name)
    return {
        "dry_run": False,
        "moved": True,
        "project": slug,
        "from": str(project_dir),
        "to": str(trash_target),
        "restore_command": f"che project restore {trash_name}",
    }


def restore_project(trash_slug: str) -> Dict[str, Any]:
    return restore_workspace(trash_slug)


def ensure_worktree_l3_dirs(worktree_root: str, *, session_id: str = "auto-worktree-bootstrap") -> Dict[str, Any]:
    if not worktree_root:
        print("ensure_worktree_l3_dirs: worktree_root required.", file=sys.stderr)
        sys.exit(2)
    wt = Path(worktree_root).resolve()
    paths = ensure_session_dirs(str(wt), session_id, cwd_override=str(wt))
    return {
        "bootstrapped": True,
        "worktree_root": str(wt),
        "worktree_slug": resolve_worktree_slug(str(wt)),
        "CHE_WORKSPACE_SHARED": paths.get("CHE_WORKSPACE_SHARED"),
        "CHE_WORKTREE_DIR": paths.get("CHE_WORKTREE_DIR"),
    }


def cleanup_worktree_l3(worktree_root: str) -> Dict[str, Any]:
    if not worktree_root:
        print("cleanup_worktree_l3: worktree_root required.", file=sys.stderr)
        sys.exit(2)
    wt = Path(worktree_root).resolve()
    worktree_slug = resolve_worktree_slug(str(wt))
    workspace_name = resolve_workspace_name(str(wt))
    project_slug = project_slug_from_git_origin(str(wt))
    ws_root = get_workspaces_root()
    wt_l3_parent = ws_root / "workspaces" / workspace_name / project_slug / "worktrees" / worktree_slug
    if not wt_l3_parent.is_dir():
        return {"nothing_to_clean": True, "expected_l3_path": str(wt_l3_parent)}
    ts = _ts_slug()
    trash_name = f"worktree--{worktree_slug}--{ts}"
    trash_target = _trash_dir() / trash_name
    shutil.move(str(wt_l3_parent), str(trash_target))
    _write_manifest(trash_target, kind="worktree", original_path=str(wt_l3_parent), slug=trash_name)
    return {
        "moved_to_trash": True,
        "worktree_slug": worktree_slug,
        "from": str(wt_l3_parent),
        "to": str(trash_target),
        "restore_command": f"che workspace restore {trash_name}",
    }
